server:
  port: 8083
  servlet:
    context-path: /guideServer

spring:
  data:
    mongodb:
      database: nextTravelGuideDatabase
      host: localhost
      port: 27017
  application:
    name: GUIDE-SERVER
